# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network requests when you run `pod install`.
# Uncomment the following line to disable this.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter integration will be handled by the Flutter tool
  # No need for manual pod installation
end